services:
  auth-service:
    image: auth-service:latest # Use the image you built for your API server
    build:
      context: .
    ports:
      - 5000:5000 # Map port 3000 on the host to port 3000 in the container
    env_file:
      - .env.prod # specify the production environment file
